# This CI configuration for relative benchmarks is based on the research done
# for scikit-image's implementation available here:
# https://github.com/scikit-image/scikit-image/blob/9bdd010a8/.github/workflows/benchmarks.yml#L1
# Blog post with the rationale: https://labs.quansight.org/blog/2021/08/github-actions-benchmarks/

name: Benchmark

on:
  pull_request:
    # types: [labeled]
  workflow_dispatch:

# This is the main configuration section that needs to be fine tuned to napari's needs
# All the _THREADS options is just to make the benchmarks more robust by not using parallelism
env:
  OPENBLAS_NUM_THREADS: "1"
  MKL_NUM_THREADS: "1"
  OMP_NUM_THREADS: "1"
  ASV_SKIP_SLOW: "1" # Custom flag implemented in some tests
  ASV_OPTIONS: "--split --show-stderr --factor 1.5" # modify as needed

jobs:
  benchmark:
    # if: ${{ github.event.label.name == 'run-benchmark' && github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    name: ASV
    runs-on: ubuntu-20.04
    steps:
      # We need the full repo to avoid this issue
      # https://github.com/actions/checkout/issues/23
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v3
        name: Install Python
        with:
          python-version: "3.9"

      - name: Setup some dependencies
        run: |
          python -m pip install asv virtualenv

      - name: Run benchmarks
        id: benchmark
        env:
          # asv will checkout commits, which might contain LFS artifacts; ignore those errors since
          # they are probably just documentation PNGs not needed here anyway
          GIT_LFS_SKIP_SMUDGE: 1
        run: |
          set -x

          # ID this runner
          asv machine --yes

          echo "Baseline:  ${{ github.event.pull_request.base.sha }} (${{ github.event.pull_request.base.label }})"
          echo "Contender: ${GITHUB_SHA} (${{ github.event.pull_request.head.label }})"

          # Run benchmarks for current commit against base
          asv continuous $ASV_OPTIONS ${{ github.event.pull_request.base.sha }} ${GITHUB_SHA} \
              | sed "/Traceback \|failed$\|PERFORMANCE DECREASED/ s/^/::error::/" \
              | tee benchmarks.log

          # Report and export results for subsequent steps
          if grep "Traceback \|failed\|PERFORMANCE DECREASED" benchmarks.log > /dev/null ; then
              exit 1
          fi

      - name: Add instructions to artifact
        if: always()
        run: cp benchmarks.log .asv/results/

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: asv-benchmark-results-${{ github.sha }}-${{ runner.os }}
          path: .asv/results
